title: Glowyr Inc.
tagline: Scientific and Technical Research
description: >-
  Glowyr Inc. are experts in medical and biomedical science.

url: https://glowyr.ca
baseurl: ""

# Use TeXt theme as a gem
theme: jekyll-text-theme

# Basics
timezone: Etc/UTC
lang: en

permalink: /:title/

# Author/site metadata
author:
  name: Glowyr Inc.
  url: https://glowyr.ca

# Contact
email: contact@glowyr.ca

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins supported by GitHub Actions build (no GitHub Pages restrictions when using artifacts)
plugins: []

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

collections:
  posts:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

include:
  - CNAME
